'use client';

import {
  Smartphone,
  FileText,
  Palette,
  Image,
  Server,
  Monitor,
  Shield,
  GitBranch,
  TestTube2,
  Download,
  Upload,
  Share2,
  Edit,
  CheckCircle2,
  Loader2,
  AlertCircle,
  RefreshCw,
  Folder,
  File,
  ChevronRight,
  Package,
} from 'lucide-react';
import { useState, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { useReviewGenerate } from '@/store/wizard-store';
import {
  APP_OPTIONS,
  GENERATION_STAGES,
  type GenerationStage,
} from '@/types/wizard';
import { cn } from '@/lib/utils';

export function Step10ReviewGenerate() {
  const {
    isGenerating,
    generationProgress,
    downloadUrl,
    downloadFileName,
    downloadSize,
    error,
    summary,
    startGeneration,
    setGenerationProgress,
    setDownloadReady,
    setGenerationError,
    resetGeneration,
    exportConfig,
    importConfig,
    resetWizard,
    setCurrentStep,
  } = useReviewGenerate();

  const [showImportDialog, setShowImportDialog] = useState(false);

  const handleExport = useCallback(() => {
    const json = exportConfig();
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${summary.step2.projectName || 'mifos-app'}-config.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, [exportConfig, summary.step2.projectName]);

  const handleImport = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const json = e.target?.result as string;
        const success = importConfig(json);
        if (!success) {
          alert('Failed to import configuration. Invalid format.');
        }
      };
      reader.readAsText(file);
    }
    setShowImportDialog(false);
  }, [importConfig]);

  const handleGenerate = useCallback(async () => {
    startGeneration();

    const stages: Array<{ stage: GenerationStage; message: string }> = [
      { stage: 'validating', message: 'Validating configuration...' },
      { stage: 'generating-gradle', message: 'Generating Gradle files...' },
      { stage: 'generating-theme', message: 'Creating theme files...' },
      { stage: 'processing-icons', message: 'Processing app icons...' },
      { stage: 'generating-config', message: 'Generating configuration...' },
      { stage: 'generating-cicd', message: 'Setting up CI/CD...' },
      { stage: 'creating-zip', message: 'Creating ZIP archive...' },
    ];

    try {
      for (let i = 0; i < stages.length; i++) {
        setGenerationProgress({
          stage: stages[i].stage,
          step: i + 1,
          total: stages.length,
          message: stages[i].message,
        });
        // Simulate work
        await new Promise((resolve) => setTimeout(resolve, 500 + Math.random() * 500));
      }

      // Create a mock ZIP file (in a real app, this would be actual generation)
      const projectName = summary.step2.projectName || 'MifosApp';
      const mockContent = `# ${projectName}\n\nGenerated by MifosLaunchpad\n\nConfiguration:\n${exportConfig()}`;
      const blob = new Blob([mockContent], { type: 'application/zip' });
      const url = URL.createObjectURL(blob);

      setDownloadReady(url, `${projectName}.zip`, blob.size);
    } catch (err) {
      setGenerationError(err instanceof Error ? err.message : 'Unknown error occurred');
    }
  }, [startGeneration, setGenerationProgress, setDownloadReady, setGenerationError, summary.step2.projectName, exportConfig]);

  const handleDownload = useCallback(() => {
    if (downloadUrl && downloadFileName) {
      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = downloadFileName;
      a.click();
    }
  }, [downloadUrl, downloadFileName]);

  const handleStartNew = useCallback(() => {
    resetWizard();
    setCurrentStep(1);
  }, [resetWizard, setCurrentStep]);

  const progressPercent = (generationProgress.step / generationProgress.total) * 100;

  return (
    <div className="flex flex-col lg:flex-row gap-8">
      {/* Main Content */}
      <div className="flex-1 space-y-6">
        {/* Header */}
        <div>
          <h2 className="text-2xl font-bold">Review & Generate</h2>
          <p className="text-muted-foreground mt-1">
            Review your configuration and generate your project
          </p>
        </div>

        {/* Generation Progress/Complete State */}
        {(isGenerating || generationProgress.stage === 'complete' || error) && (
          <Card className={cn(
            'border-2',
            error ? 'border-destructive' : generationProgress.stage === 'complete' ? 'border-green-500' : 'border-primary'
          )}>
            <CardContent className="pt-6">
              {isGenerating && (
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <Loader2 className="w-5 h-5 animate-spin text-primary" />
                    <span className="font-medium">Generating Project...</span>
                  </div>
                  <Progress value={progressPercent} className="h-2" />
                  <p className="text-sm text-muted-foreground">
                    {generationProgress.message} ({generationProgress.step}/{generationProgress.total})
                  </p>
                </div>
              )}

              {generationProgress.stage === 'complete' && !isGenerating && (
                <div className="space-y-4">
                  <div className="flex items-center gap-3 text-green-600">
                    <CheckCircle2 className="w-6 h-6" />
                    <span className="font-medium text-lg">Project Generated Successfully!</span>
                  </div>
                  <div className="p-4 bg-muted/50 rounded-lg">
                    <div className="flex items-center gap-3">
                      <Package className="w-8 h-8 text-muted-foreground" />
                      <div>
                        <p className="font-medium">{downloadFileName}</p>
                        <p className="text-sm text-muted-foreground">
                          Size: {downloadSize ? (downloadSize / 1024).toFixed(1) : 0} KB
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <Button onClick={handleDownload} className="gap-2">
                      <Download className="w-4 h-4" />
                      Download ZIP
                    </Button>
                    <Button variant="outline" onClick={handleStartNew} className="gap-2">
                      <RefreshCw className="w-4 h-4" />
                      Start New Project
                    </Button>
                  </div>
                </div>
              )}

              {error && (
                <div className="space-y-4">
                  <div className="flex items-center gap-3 text-destructive">
                    <AlertCircle className="w-6 h-6" />
                    <span className="font-medium">Generation Failed</span>
                  </div>
                  <p className="text-sm text-muted-foreground">{error}</p>
                  <Button variant="outline" onClick={resetGeneration} className="gap-2">
                    <RefreshCw className="w-4 h-4" />
                    Try Again
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Configuration Summary */}
        <div className="space-y-4">
          <h3 className="font-semibold text-lg">Configuration Summary</h3>

          {/* Step 1: App Selection */}
          <SummaryCard
            title="Base Application"
            icon={<Smartphone className="w-4 h-4" />}
            stepNumber={1}
            onEdit={() => setCurrentStep(1)}
          >
            <p className="font-medium">
              {APP_OPTIONS.find((a) => a.id === summary.step1.selectedApp)?.name || 'Not selected'}
            </p>
            {summary.step1.appFeatures.length > 0 && (
              <p className="text-sm text-muted-foreground">
                Features: {summary.step1.appFeatures.join(', ')}
              </p>
            )}
          </SummaryCard>

          {/* Step 2: Project Info */}
          <SummaryCard
            title="Project Info"
            icon={<FileText className="w-4 h-4" />}
            stepNumber={2}
            onEdit={() => setCurrentStep(2)}
          >
            <div className="grid grid-cols-2 gap-2 text-sm">
              <span className="text-muted-foreground">Name:</span>
              <span>{summary.step2.displayName || summary.step2.projectName || 'Not set'}</span>
              <span className="text-muted-foreground">Package:</span>
              <span className="font-mono text-xs">{summary.step2.packageName || 'Not set'}</span>
              <span className="text-muted-foreground">Version:</span>
              <span>{summary.step2.versionName} ({summary.step2.versionCode})</span>
            </div>
          </SummaryCard>

          {/* Step 3: Branding */}
          <SummaryCard
            title="Branding & Theme"
            icon={<Palette className="w-4 h-4" />}
            stepNumber={3}
            onEdit={() => setCurrentStep(3)}
          >
            <div className="flex items-center gap-4">
              <div className="flex gap-1">
                <div
                  className="w-6 h-6 rounded border"
                  style={{ backgroundColor: summary.step3.colors.primary }}
                  title="Primary"
                />
                <div
                  className="w-6 h-6 rounded border"
                  style={{ backgroundColor: summary.step3.colors.secondary }}
                  title="Secondary"
                />
                <div
                  className="w-6 h-6 rounded border"
                  style={{ backgroundColor: summary.step3.colors.accent }}
                  title="Accent"
                />
              </div>
              <span className="text-sm text-muted-foreground">
                Dark mode: {summary.step3.darkModeEnabled ? 'Enabled' : 'Disabled'}
              </span>
            </div>
          </SummaryCard>

          {/* Step 4: App Icons */}
          <SummaryCard
            title="App Icons"
            icon={<Image className="w-4 h-4" />}
            stepNumber={4}
            onEdit={() => setCurrentStep(4)}
          >
            <div className="flex items-center gap-3">
              {summary.step4.generatedIcons?.android && (
                <img
                  src={summary.step4.generatedIcons.android['192']}
                  alt="App icon"
                  className="w-12 h-12 rounded-lg"
                />
              )}
              <div className="text-sm">
                <p>Shape: {summary.step4.iconShape}</p>
                <p className="text-muted-foreground">
                  {summary.step4.generatedIcons ? 'Icons generated' : 'No icons generated'}
                </p>
              </div>
            </div>
          </SummaryCard>

          {/* Step 5: Server Config */}
          <SummaryCard
            title="Server Configuration"
            icon={<Server className="w-4 h-4" />}
            stepNumber={5}
            onEdit={() => setCurrentStep(5)}
          >
            <p className="text-sm">
              {Object.values(summary.step5.environments).filter(e => e.enabled).length} environment(s) enabled
            </p>
            <p className="text-sm text-muted-foreground">
              Timeout: {summary.step5.connectionTimeout / 1000}s
            </p>
          </SummaryCard>

          {/* Step 6: Platforms */}
          <SummaryCard
            title="Platforms"
            icon={<Monitor className="w-4 h-4" />}
            stepNumber={6}
            onEdit={() => setCurrentStep(6)}
          >
            <div className="flex flex-wrap gap-2">
              {summary.step6.platforms.android.enabled && (
                <span className="px-2 py-1 bg-green-100 text-green-700 text-xs rounded">Android</span>
              )}
              {summary.step6.platforms.ios.enabled && (
                <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded">iOS</span>
              )}
              {summary.step6.platforms.desktop.enabled && (
                <span className="px-2 py-1 bg-purple-100 text-purple-700 text-xs rounded">Desktop</span>
              )}
              {summary.step6.platforms.web.enabled && (
                <span className="px-2 py-1 bg-orange-100 text-orange-700 text-xs rounded">Web</span>
              )}
            </div>
          </SummaryCard>

          {/* Step 7: Features & Security */}
          <SummaryCard
            title="Features & Security"
            icon={<Shield className="w-4 h-4" />}
            stepNumber={7}
            onEdit={() => setCurrentStep(7)}
          >
            <div className="flex flex-wrap gap-2 text-sm">
              {summary.step7.security.biometric && <span className="text-muted-foreground">Biometric</span>}
              {summary.step7.security.sslPinning && <span className="text-muted-foreground">SSL Pinning</span>}
              {summary.step7.twoFactorAuth && <span className="text-muted-foreground">2FA</span>}
              {summary.step7.analytics.firebase && <span className="text-muted-foreground">Firebase</span>}
            </div>
          </SummaryCard>

          {/* Step 8: CI/CD */}
          <SummaryCard
            title="CI/CD & Deployment"
            icon={<GitBranch className="w-4 h-4" />}
            stepNumber={8}
            onEdit={() => setCurrentStep(8)}
          >
            <p className="text-sm capitalize">{summary.step8.ciPlatform.replace('-', ' ')}</p>
            <div className="flex gap-2 text-xs text-muted-foreground">
              {summary.step8.firebase.enabled && <span>Firebase</span>}
              {summary.step8.playStore.enabled && <span>Play Store</span>}
              {summary.step8.appStore.enabled && <span>App Store</span>}
            </div>
          </SummaryCard>

          {/* Step 9: Code Quality */}
          <SummaryCard
            title="Code Quality"
            icon={<TestTube2 className="w-4 h-4" />}
            stepNumber={9}
            onEdit={() => setCurrentStep(9)}
          >
            <div className="flex flex-wrap gap-2 text-sm text-muted-foreground">
              {summary.step9.testing.unitTests && <span>Unit Tests</span>}
              {summary.step9.linting.detekt && <span>Detekt</span>}
              {summary.step9.linting.ktlint && <span>ktlint</span>}
              {summary.step9.coverage.enabled && <span>Coverage {summary.step9.coverage.minimumPercent}%</span>}
            </div>
          </SummaryCard>
        </div>

        {/* Actions */}
        <div className="flex flex-wrap gap-3">
          <Button variant="outline" onClick={handleExport} className="gap-2">
            <Download className="w-4 h-4" />
            Export JSON
          </Button>
          <label>
            <Button variant="outline" asChild className="gap-2 cursor-pointer">
              <span>
                <Upload className="w-4 h-4" />
                Import JSON
              </span>
            </Button>
            <input
              type="file"
              accept=".json"
              className="hidden"
              onChange={handleImport}
            />
          </label>
        </div>

        {/* Generate Button */}
        {generationProgress.stage === 'idle' && (
          <Button
            size="lg"
            onClick={handleGenerate}
            className="w-full gap-2"
            disabled={!summary.step1.selectedApp}
          >
            <Package className="w-5 h-5" />
            Generate Project
          </Button>
        )}
      </div>

      {/* File Tree Preview - Desktop Only */}
      <div className="hidden lg:block w-[320px] shrink-0">
        <FileTreePreview projectName={summary.step2.projectName || 'MifosApp'} />
      </div>
    </div>
  );
}

// ============================================
// Summary Card Component
// ============================================

interface SummaryCardProps {
  title: string;
  icon: React.ReactNode;
  stepNumber: number;
  onEdit: () => void;
  children: React.ReactNode;
}

function SummaryCard({ title, icon, stepNumber, onEdit, children }: SummaryCardProps) {
  return (
    <Card>
      <CardContent className="pt-4 pb-4">
        <div className="flex items-start justify-between">
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary shrink-0">
              {icon}
            </div>
            <div className="space-y-1">
              <p className="font-medium text-sm">{title}</p>
              {children}
            </div>
          </div>
          <Button variant="ghost" size="sm" onClick={onEdit} className="shrink-0">
            <Edit className="w-4 h-4" />
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// ============================================
// File Tree Preview Component
// ============================================

function FileTreePreview({ projectName }: { projectName: string }) {
  return (
    <div className="space-y-4 sticky top-24">
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <Folder className="w-4 h-4" />
            Generated Files
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="font-mono text-sm space-y-1">
            <TreeItem name={projectName} type="folder" level={0}>
              <TreeItem name="composeApp" type="folder" level={1}>
                <TreeItem name="src" type="folder" level={2}>
                  <TreeItem name="commonMain" type="folder" level={3} />
                  <TreeItem name="androidMain" type="folder" level={3} />
                  <TreeItem name="iosMain" type="folder" level={3} />
                </TreeItem>
                <TreeItem name="build.gradle.kts" type="file" level={2} />
              </TreeItem>
              <TreeItem name="androidApp" type="folder" level={1}>
                <TreeItem name="src" type="folder" level={2} />
                <TreeItem name="build.gradle.kts" type="file" level={2} />
              </TreeItem>
              <TreeItem name="iosApp" type="folder" level={1}>
                <TreeItem name="iosApp.xcodeproj" type="folder" level={2} />
              </TreeItem>
              <TreeItem name=".github" type="folder" level={1}>
                <TreeItem name="workflows" type="folder" level={2}>
                  <TreeItem name="build.yml" type="file" level={3} />
                  <TreeItem name="release.yml" type="file" level={3} />
                </TreeItem>
              </TreeItem>
              <TreeItem name="gradle" type="folder" level={1} />
              <TreeItem name="build.gradle.kts" type="file" level={1} />
              <TreeItem name="settings.gradle.kts" type="file" level={1} />
              <TreeItem name="README.md" type="file" level={1} />
            </TreeItem>
          </div>
          <p className="text-xs text-muted-foreground mt-4">
            ~50+ files will be generated
          </p>
        </CardContent>
      </Card>
    </div>
  );
}

interface TreeItemProps {
  name: string;
  type: 'file' | 'folder';
  level: number;
  children?: React.ReactNode;
}

function TreeItem({ name, type, level, children }: TreeItemProps) {
  const [expanded, setExpanded] = useState(level < 2);
  const hasChildren = !!children;

  return (
    <div>
      <div
        className={cn(
          'flex items-center gap-1 py-0.5 hover:bg-muted/50 rounded cursor-pointer',
          level > 0 && 'ml-4'
        )}
        onClick={() => hasChildren && setExpanded(!expanded)}
      >
        {type === 'folder' ? (
          <>
            <ChevronRight
              className={cn(
                'w-3 h-3 transition-transform',
                expanded && 'rotate-90',
                !hasChildren && 'invisible'
              )}
            />
            <Folder className="w-4 h-4 text-blue-500" />
          </>
        ) : (
          <>
            <span className="w-3" />
            <File className="w-4 h-4 text-muted-foreground" />
          </>
        )}
        <span className="text-xs">{name}</span>
      </div>
      {expanded && children}
    </div>
  );
}
